# GET http://localhost:5000/api/user/viewuser
# content-type: application/json


POST  http://localhost:5000/api/user/adduser
content-type: application/json


{
      "user_name":"Prashant",
      "user_email":"prsashant@gmail.com",
      "user_dob":"1999-10-10",
      "gender":"male"
}